"use client";

import { useState } from "react";
import { Icon } from "@/components/Icon";
import type { Project } from "@/lib/projects";
import { AgentTeam } from "@/components/app/AgentTeam";

const SAMPLE_CODE = (name: string) => `// app/page.tsx — generated by Emergent
import { getItems } from "@/lib/api";
import { Card } from "@/components/Card";

export default async function ${name}Home() {
  const items = await getItems();
  return (
    <main className="mx-auto max-w-5xl p-8">
      <h1 className="text-3xl font-semibold">${name}</h1>
      <div className="mt-6 grid gap-4 sm:grid-cols-3">
        {items.map((item) => (
          <Card key={item.id} item={item} />
        ))}
      </div>
    </main>
  );
}`;

export function PreviewPane({
  project,
  building,
}: {
  project: Project;
  building: boolean;
}) {
  const [tab, setTab] = useState<"agents" | "preview" | "code">("agents");

  // Once building starts, nudge the user toward the agent view; after, preview.
  const effectiveTab = building ? "agents" : tab === "agents" ? "preview" : tab;

  return (
    <div className="flex h-full flex-col">
      {/* Tab bar */}
      <div className="flex items-center justify-between border-b border-line px-3">
        <div className="flex">
          {(
            [
              ["agents", "Agents", "users"],
              ["preview", "Preview", "play"],
              ["code", "Code", "code"],
            ] as const
          ).map(([id, label, icon]) => (
            <button
              key={id}
              onClick={() => setTab(id)}
              className={`flex items-center gap-1.5 border-b-2 px-3 py-3 text-sm transition-colors ${
                effectiveTab === id
                  ? "border-brand-500 text-white"
                  : "border-transparent text-white/45 hover:text-white/80"
              }`}
            >
              <Icon name={icon} size={15} />
              {label}
            </button>
          ))}
        </div>
        {project.status === "live" && (
          <div className="hidden items-center gap-2 pr-1 sm:flex">
            <a
              href="#"
              onClick={(e) => e.preventDefault()}
              className="chip hover:border-brand-500/50 hover:text-white"
            >
              <Icon name="globe" size={13} />
              {project.name.toLowerCase()}.emergent.app
            </a>
            <a
              href="#"
              onClick={(e) => e.preventDefault()}
              className="btn btn-ghost p-1.5"
              title="Open on GitHub"
            >
              <Icon name="github" size={16} />
            </a>
          </div>
        )}
      </div>

      {/* Content */}
      <div className="min-h-0 flex-1 overflow-y-auto p-4">
        {effectiveTab === "agents" && (
          <div>
            <div className="mb-3 flex items-center justify-between">
              <h3 className="text-sm font-semibold text-white">Agent team</h3>
              <span className="text-xs text-white/40">
                {building ? "Working…" : "Ready"}
              </span>
            </div>
            <AgentTeam running={building} />
          </div>
        )}

        {effectiveTab === "preview" && (
          <BrowserFrame project={project} building={building} />
        )}

        {effectiveTab === "code" && (
          <pre className="overflow-x-auto rounded-xl border border-line bg-ink-950 p-4 font-mono text-xs leading-relaxed text-white/70">
            <code>{SAMPLE_CODE(project.name)}</code>
          </pre>
        )}
      </div>
    </div>
  );
}

function BrowserFrame({
  project,
  building,
}: {
  project: Project;
  building: boolean;
}) {
  return (
    <div className="overflow-hidden rounded-xl border border-line bg-ink-900">
      <div className="flex items-center gap-2 border-b border-line bg-ink-850 px-3 py-2">
        <span className="h-2.5 w-2.5 rounded-full bg-white/20" />
        <span className="h-2.5 w-2.5 rounded-full bg-white/20" />
        <span className="h-2.5 w-2.5 rounded-full bg-white/20" />
        <div className="ml-2 flex-1 rounded-md bg-ink-900 px-3 py-1 text-center font-mono text-[11px] text-white/40">
          {project.name.toLowerCase()}.emergent.app
        </div>
      </div>
      <div className={`bg-gradient-to-br ${project.accent} p-6`}>
        {building ? (
          <div className="grid h-56 place-items-center">
            <div className="flex flex-col items-center gap-3 text-white/70">
              <span className="h-6 w-6 animate-spin rounded-full border-2 border-white/60 border-t-transparent" />
              <span className="text-sm">Building your app…</span>
            </div>
          </div>
        ) : (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="h-4 w-28 rounded bg-white/30" />
              <div className="flex gap-2">
                <div className="h-7 w-16 rounded-lg bg-white/15" />
                <div className="h-7 w-20 rounded-lg bg-white/30" />
              </div>
            </div>
            <div className="h-6 w-2/3 rounded bg-white/25" />
            <div className="h-3 w-1/2 rounded bg-white/15" />
            <div className="grid grid-cols-3 gap-3 pt-2">
              {[0, 1, 2, 3, 4, 5].map((i) => (
                <div key={i} className="rounded-lg bg-white/10 p-3">
                  <div className="h-10 w-full rounded bg-white/15" />
                  <div className="mt-2 h-2 w-3/4 rounded bg-white/20" />
                  <div className="mt-1.5 h-2 w-1/2 rounded bg-white/10" />
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
